import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { startServer } from '../src/server/index.js';
const dir=await mkdtemp(path.join(tmpdir(),'workbench-v2-ui-'));
const runtime=await startServer({dataDir:dir,port:4320,staticDir:path.resolve('dist')});
const modelCalls:{prompt:string,images:number,schema:unknown}[]=[];
// Explicit test double: exercise the real HTTP/import/media/pipeline/UI without a paid model call.
(runtime.service as any).codex=async (_job:unknown,prompt:string,images:string[]=[],schema:any)=>{
 modelCalls.push({prompt:prompt.slice(0,160),images:images.length,schema});
 if(schema?.properties?.episodes){const json={summary:'模拟总剧本初步分析',episodes:[{name:'第一集',startLine:1,endLine:2},{name:'第二集',startLine:3,endLine:4}]};return {text:JSON.stringify(json),json,images:[]};}
 const assets=runtime.store.state.assets.filter(a=>!['original-frame','image-candidate','assembled-source'].includes(a.role));
 const fill=(spec:any,key='',asset:any=assets[0]):any=>{
  if(spec?.enum)return spec.enum.includes(asset?.role)?asset.role:spec.enum[0];
  if(spec?.type==='object')return Object.fromEntries(Object.entries(spec.properties||{}).map(([k,v])=>[k,fill(v,k,asset)]));
  if(spec?.type==='array'){
   if(['issues','uncertainties','warnings'].includes(key))return [];
   if(/referenceIds/.test(key))return assets.filter(a=>a.role!=='source'&&a.kind==='image').map(a=>a.id);
   if(spec.items?.type==='object'&&/assets|materials|items/.test(key))return assets.map(a=>fill(spec.items,'',a));
   return [];
  }
  if(spec?.type==='boolean')return true;
  if(spec?.type==='number'||spec?.type==='integer')return .95;
  if(key==='id'||key==='assetId')return asset?.id||'';
  if(key==='role')return asset?.role||'reference';
  if(key==='scene')return '同一场景';
  if(key==='name')return asset?.name||'验收镜头';
  return '流程验收替身：保留实拍构图与人物；正式生产由 Codex 返回真实分析。';
 };
 const json=schema?fill(schema):undefined;
 return {text:json?JSON.stringify(json):'流程验收替身：整集提示词，保留源片表演与镜头。',json,images:[]};
};
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1536,height:1000}});page.setDefaultTimeout(15000);
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400 && /\/api\/|\/media\//.test(r.url())) errors.push(`${r.status()} ${r.url()}`);});
try{
 await page.goto(runtime.url);
 await expect(page.locator('.page-projects')).toBeVisible();
 await expect(page.locator('.timeline')).toHaveCount(0);
 await page.screenshot({path:'docs/v2/verification/projects.png',fullPage:true});
 await page.getByRole('button',{name:'＋ 新建大项目',exact:true}).click();
 await page.getByLabel('大项目名称',{exact:true}).fill('第二轮产品验收');
 await page.getByLabel('上传总剧本',{exact:true}).setInputFiles({name:'总剧本.txt',mimeType:'text/plain',buffer:Buffer.from('第一集\n第一集故事\n第二集\n第二集故事')});
 await expect(page.getByLabel('总剧本内容（可直接粘贴）',{exact:true})).toHaveValue('第一集\n第一集故事\n第二集\n第二集故事');
 await page.getByRole('button',{name:'创建并分析总剧本 →',exact:true}).click();
 await expect(page.locator('.episode-row')).toHaveCount(2);
 assert.equal(runtime.store.state.episodes[0].script,'第一集\n第一集故事');
 assert.equal(runtime.store.state.episodes[1].script,'第二集\n第二集故事');
 await page.screenshot({path:'docs/v2/verification/episodes.png',fullPage:true});
 await page.locator('.episode-row').first().getByRole('button').click();
 await expect(page.getByText('原视频',{exact:true}).first()).toBeVisible();
 await expect(page.locator('.timeline')).toHaveCount(0);
 const prior=JSON.parse(await readFile('docs/verification/media-smoke.json','utf8'));
 await page.getByLabel('上传原视频',{exact:true}).setInputFiles(path.join(prior.dataDir,'real-source-excerpt.mp4'));
 await expect.poll(()=>runtime.store.state.assets.filter(a=>a.role==='source').length).toBe(1);
 await expect.poll(()=>runtime.store.state.jobs.some(j=>['queued','running'].includes(j.status))).toBe(false);
 await page.getByRole('button',{name:'移除 real-source-excerpt.mp4',exact:true}).click();
 await expect.poll(()=>runtime.store.state.assets.filter(a=>a.role==='source').length).toBe(0);
 assert.equal(runtime.store.state.shots.length,0);
 await page.getByLabel('上传原视频',{exact:true}).setInputFiles(path.join(prior.dataDir,'real-source-excerpt.mp4'));
 await expect.poll(()=>runtime.store.state.assets.filter(a=>a.role==='source').length).toBe(1);
 await expect(page.getByLabel('本集剧本',{exact:true})).toHaveValue('第一集\n第一集故事');
 await expect(page.getByLabel('上传剧本',{exact:true})).toHaveCount(0);
 await expect(page.getByLabel('上传素材',{exact:true})).toBeEnabled();
 await page.getByLabel('上传素材',{exact:true}).setInputFiles(path.resolve('docs/ai-evidence/codex-image-smoke.png'));
 await expect.poll(()=>runtime.store.state.assets.filter(a=>a.role==='reference').length).toBe(1);
 await expect(page.getByRole('button',{name:'继续已有制作',exact:true})).toHaveCount(0);
 await page.screenshot({path:'docs/v2/verification/upload.png',fullPage:true});
 await page.getByRole('button',{name:/Codex 自动整理/}).click();
 await expect(page.locator('.page-images')).toBeVisible({timeout:60000});
 assert.equal(runtime.store.state.episodes[0].preparation?.status,'ready');
 assert.ok(modelCalls.length>=3,'Must invoke material, shot and full-prompt compilation');
 assert.ok(runtime.store.state.shots.every(sh=>sh.sourceFrameId && sh.sourceFrameTime===sh.in && sh.confirmed && sh.imagePrompt && sh.videoPrompt));
 await expect(page.locator('.timeline')).toHaveCount(0);
 await expect(page.getByText('确认镜头事实',{exact:true})).toHaveCount(0);
 await page.screenshot({path:'docs/v2/verification/images.png',fullPage:true});
 await page.getByRole('button',{name:'素材板',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'素材板'}).locator('.material-tile')).toHaveCount(2);
 await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();
 await page.getByRole('button',{name:`查看 ${runtime.store.state.shots[0].name}`,exact:true}).click();
 await page.getByLabel('上传候选图',{exact:true}).setInputFiles(path.resolve('docs/ai-evidence/codex-image-smoke.png'));
 await expect.poll(()=>runtime.store.state.takes.filter(t=>t.kind==='image').length).toBe(1);
 await page.getByRole('button',{name:'选定此图 →',exact:true}).click();
 const imageTake=runtime.store.state.takes.find(t=>t.kind==='image')!;
 await expect.poll(()=>runtime.store.state.shots[0].approvedImageId).toBe(imageTake.id);
 await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();
 await expect(page.getByAltText(`${runtime.store.state.shots[0].name} 选定分镜图`)).toHaveAttribute('src',`/media/${imageTake.assetId}`);
 const skip=page.getByRole('button',{name:/跳过.*生图|跳过.*视频/}).first();await skip.click();
 await expect(page.locator('.page-video')).toBeVisible();await expect(page.locator('.timeline')).toBeVisible();
 assert.ok(runtime.store.state.segments.length>0);
 assert.ok(runtime.store.state.segments.every(s=>s.prompt && s.duration<=30));
 await page.getByLabel('导入视频版本',{exact:true}).setInputFiles(path.join(prior.dataDir,'real-source-excerpt.mp4'));
 await expect.poll(()=>runtime.store.state.takes.filter(t=>t.kind==='video').length).toBe(1);
 await expect(page.locator('.dual-viewer video, .studio video')).toHaveCount(2);
 await page.getByRole('button',{name:'播放',exact:true}).click();
 await expect.poll(async()=>Number(await page.getByLabel('播放位置',{exact:true}).inputValue())).toBeGreaterThan(.3);
 await page.getByRole('button',{name:'暂停',exact:true}).click();
 await expect(page.locator('.inline-error')).toHaveCount(0);
 await page.getByRole('button',{name:'选择此版本用于成片',exact:true}).click();
 const videoTake=runtime.store.state.takes.find(t=>t.kind==='video')!;
 await expect.poll(()=>runtime.store.state.segments[0].selectedTakeId).toBe(videoTake.id);
 // Exercise persisted timeline changes with real input media.
 const initialClips=structuredClone(runtime.store.state.segments[0].clips);
 await page.locator('.ruler').click({position:{x:27,y:8}});
 await page.locator('.timeline').getByRole('button',{name:/拆分/}).click();
 await expect.poll(()=>runtime.store.state.segments[0].clips.length).toBe(initialClips.length+1);
 await page.locator('.timeline').getByRole('button',{name:/撤销/}).click();
 await expect.poll(()=>runtime.store.state.segments[0].clips).toEqual(initialClips);
 await page.mouse.move(1510,740);
 await page.screenshot({path:'docs/v2/verification/video.png',fullPage:true});
 await page.reload();
 await page.locator('.project-card').filter({hasText:'第二轮产品验收'}).click();
 await page.locator('.episode-row').first().getByRole('button').click();
 await expect(page.locator('.page-images')).toBeVisible();
 await expect(page.getByAltText(`${runtime.store.state.shots[0].name} 选定分镜图`)).toBeVisible();
 await page.getByRole('button',{name:'视频制作',exact:true}).click();
 await expect(page.locator('.page-video')).toBeVisible();
 await expect(page.locator('.inline-error')).toHaveCount(0);
 await page.locator('.project-breadcrumb button').click();
 await page.getByRole('button',{name:'＋ 添加集',exact:true}).click();
 await page.getByLabel('集名称',{exact:true}).fill('番外');
 await page.getByLabel('本集原视频（必选）',{exact:true}).setInputFiles(path.join(prior.dataDir,'real-source-excerpt.mp4'));
 await page.getByLabel('本集素材 / 资产（可多选、稍后补充）',{exact:true}).setInputFiles(path.resolve('docs/ai-evidence/codex-image-smoke.png'));
 await page.getByRole('button',{name:'添加集并上传素材 →',exact:true}).click();
 await expect(page.locator('.page-import')).toBeVisible();
 const manual=runtime.store.state.episodes.find(e=>e.name==='番外')!;
 assert.equal(manual.projectId,runtime.store.state.projects[0].id);
 assert.equal(runtime.store.state.assets.filter(a=>a.episodeId===manual.id).length,2);
 assert.deepEqual(errors,[]);
 await writeFile('docs/v2/verification/flow.json',JSON.stringify({passed:true,errors,modelCalls:modelCalls.length,shots:runtime.store.state.shots.length,checked:['大项目上传总剧本、初步分析、自动识别并保留各集原文','横排行集列表与手动新增集同时上传原视频和资产','项目首页不暴露编辑器','三类上传与正确存储','错传原片移除并重新上传','准备前无绕过入口','一次点击自动分析拆镜首帧与提示词','自动进入独立图片工作台','无逐镜重复确认','视频页单独时间线与自动组段','素材板三类分析可查','人工候选上传与选定绑定','视频版本导入、双屏播放和暂停无误报','时间线拆分撤销保存','刷新恢复选定分镜与视频入口'],note:'实际HTTP/FFmpeg/UI，Codex使用显式替身，未消费真实模型额度'},null,2));
 console.log('V2 complete product flow passed.');
} catch(error){await page.screenshot({path:'docs/v2/verification/failure.png',fullPage:true});console.log((await page.locator('body').innerText()).slice(0,9000));throw error;}
finally{await browser.close();await runtime.close();await rm(dir,{recursive:true,force:true});}
