import { useCallback, useEffect, useState } from 'react';
import type { Asset, Episode } from '../shared/types';
import { downloadText, Field, media, Modal, safeAction, thumbnail, type Command, type State } from './common';
import { Jobs, SettingsPanel } from './Panels';
import { ImageWorkspace } from './ImageWorkbench';
import { EpisodeVisualRequirements } from './VisualRequirements';
import { Projects } from './Projects';
import { VideoWorkspace } from './VideoWorkspace';

type Page = 'projects' | 'import' | 'prepare' | 'images' | 'video';
type Preparation = NonNullable<Episode['preparation']>;
export type PreparedEpisode = Episode & { preparation?: Preparation; materialAnalysis?: string; workflowVersion?: number };
export type Upload = (files: FileList | File[], role: string, extra?: Record<string, string>) => Promise<void>;
export const assetRoles: Record<string,string> = { source: '原视频', script: '剧本', reference: '参考资产', scene: '场景', character: '人物', costume: '服装', prop: '道具', look: '影调参考' };

export default function App() {
  const [projectId, setProjectId] = useState('');
  const [state, setState] = useState<State | null>(null), [page, setPage] = useState<Page>('projects'), [episodeId, setEpisodeId] = useState('');
  const [dialog, setDialog] = useState<'create' | 'settings' | 'jobs' | 'materials' | 'export' | 'visual' | 'skip-images' | null>(null), [error, setError] = useState(''), [connected, setConnected] = useState(false), [pending, setPending] = useState(0), [importing, setImporting] = useState(false), [notice, setNotice] = useState('');
  const accept = useCallback((next: State) => setState(old => !old || next.revision >= old.revision ? next : old), []);
  const refresh = useCallback(async () => { try { const response = await fetch('/api/state'); const data = await response.json(); if (!response.ok) throw new Error(data.error || '无法连接工作区'); accept(data); setConnected(true); } catch { setConnected(false); } }, [accept]);
  useEffect(() => { void fetch('/api/session').then(refresh).catch(refresh); const timer = setInterval(() => void refresh(), 1500); return () => clearInterval(timer); }, [refresh]);
  const command: Command = useCallback(async (type, payload = {}) => { setPending(n => n + 1); try { const response = await fetch('/api/command', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type, ...payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || '操作失败'); if (data.state) accept(data.state); return data.result; } catch (e) { setError(e instanceof Error ? e.message : String(e)); throw e; } finally { setPending(n => n - 1); } }, [accept]);
  const episode = state?.episodes.find(e => e.id === episodeId) as PreparedEpisode | undefined;
  const currentShots = state?.shots.filter(s => s.episodeId === episodeId) || [];
  const preparation = episode?.preparation;
  useEffect(() => { if (page === 'prepare' && preparation?.status === 'ready') setPage('images'); }, [page, preparation?.status]);
  useEffect(() => { if (page === 'prepare' && preparation?.status === 'failed' && currentShots.length && currentShots.every(s => s.sourceFrameId && s.facts.startsWith('已跳过 AI 分析'))) setPage('images'); }, [page, preparation?.status, currentShots]);
  useEffect(() => { if (!notice) return; const id = setTimeout(() => setNotice(''), 5500); return () => clearTimeout(id); }, [notice]);
  const upload: Upload = async (files, role, extra = {}) => { if (!files.length || !episodeId) return; setImporting(true); try { const form = new FormData(); Array.from(files).forEach(f => form.append('files', f)); form.append('episodeId', episodeId); form.append('role', role); Object.entries(extra).forEach(([key, value]) => form.append(key, value)); const response = await fetch('/api/import', { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || '导入失败'); if (data.state) accept(data.state); if (data.errors?.length) setError(data.errors.join('\n')); else setNotice(`已导入 ${files.length} 个文件`); } catch (e) { setError(e instanceof Error ? e.message : String(e)); throw e; } finally { setImporting(false); } };
  const prepare = async (script?: string, skipAnalysis = false) => { if (script !== undefined) await command('episode.update', { id: episodeId, patch: { script } }); await command(skipAnalysis ? 'episode.prepareWithoutAnalysis' : 'episode.prepare', { episodeId }); setPage('prepare'); };
  async function enterVideo(skip = false) { if (skip) await command('episode.update', { id: episodeId, patch: { skipImages: true } }); if (!state?.segments.some(s => s.episodeId === episodeId)) await command('episode.group', { episodeId }); setPage('video'); }
  function open(ep: PreparedEpisode, legacy = false) { const localOnly = state?.shots.some(s => s.episodeId === ep.id) && state.shots.filter(s => s.episodeId === ep.id).every(s => s.sourceFrameId && s.facts.startsWith('已跳过 AI 分析')); setEpisodeId(ep.id); setError(''); setPage(localOnly || ep.preparation?.status === 'ready' || legacy ? 'images' : ep.preparation?.status === 'running' || ep.preparation?.status === 'pending' || ep.preparation?.status === 'paused' ? 'prepare' : 'import'); }
  if (!state) return <div className="boot"><div className="brand-symbol">与</div><h1>与光 · AI 实拍工作台</h1><p>{connected ? '读取项目…' : '正在连接本地工作区…'}</p><button onClick={() => void refresh()}>重新连接</button></div>;
  const assets = state.assets.filter(a => a.episodeId === episodeId), shots = state.shots.filter(s => s.episodeId === episodeId), active = state.jobs.filter(j => ['queued', 'running', 'waiting', 'uncertain'].includes(j.status));
  const videoReady = shots.length > 0 && shots.every(s => s.skipImage || episode?.skipImages || state.takes.some(t => t.id === s.approvedImageId && t.status === 'approved' && t.sourceRevision === s.revision));
  const requestVideo = async () => { if (videoReady) await enterVideo(); else setDialog('skip-images'); };
  return <div className={`product-shell page-${page}`}><header className="product-header"><button className="product-brand" onClick={() => setPage('projects')}><span className="brand-symbol">与</span><strong>与光 <span>AI 实拍工作台</span></strong></button>{episode && page !== 'projects' && <div className="project-breadcrumb"><button className="text-button" onClick={() => setPage('projects')}>{state.projects?.find(p=>p.id===projectId)?.name || '所有项目'}</button><span>/</span><strong>{episode.name}</strong></div>}<div className="header-actions"><span className="muted">{!connected ? '连接中断' : pending || importing ? '保存中…' : '本地已保存'}</span><button className="text-button" onClick={() => setDialog('jobs')}>任务{active.length ? ` · ${active.length}` : ''}</button><button className="text-button" onClick={() => setDialog('settings')}>设置</button></div></header>
  {!connected && <div className="connection-banner" role="alert">本地服务连接中断，正在重连。<button onClick={() => void refresh()}>立即重试</button></div>}
  {page === 'projects' && <Projects state={state} command={command} selected={projectId} select={setProjectId} open={ep=>{setProjectId(ep.projectId||'');open(ep,!ep.workflowVersion&&state.shots.some(s=>s.episodeId===ep.id));}}/>}
  {episode && page === 'import' && <ImportPage key={episode.id} episode={episode} assets={assets} upload={upload} importing={importing} pending={pending > 0} start={prepare} command={command} hasShots={!episode.workflowVersion && shots.length > 0} continueLegacy={() => setPage('images')} />}
  {episode && page === 'prepare' && <PreparationPage episode={episode} state={state} command={command} retry={() => prepare()} skip={() => prepare(undefined, true)} materials={() => setPage('import')} />}
  {episode && ['images', 'video'].includes(page) && <><nav className="workspace-nav"><div className="workspace-switch"><button className={page === 'images' ? 'active' : ''} onClick={() => setPage('images')}>分镜图</button><button className={page === 'video' ? 'active' : ''} disabled={!shots.length} onClick={() => safeAction(requestVideo)}>视频制作</button></div><div className="row"><button className="text-button" onClick={() => setDialog('visual')}>本集 / 场景光影</button><button className="text-button" onClick={() => setDialog('materials')}>素材板</button>{page === 'video' && <button className="primary" onClick={() => setDialog('export')}>导出成片 ↗</button>}</div></nav>{page === 'images' ? <ImageWorkspace state={state} episode={episode} command={command} upload={upload} importing={importing} next={requestVideo} addMaterials={() => setPage('import')} /> : <VideoWorkspace state={state} episode={episode} command={command} upload={upload} importing={importing} />}</>}
  {dialog === 'create' && <CreateProject command={command} close={() => setDialog(null)} created={id => { setEpisodeId(id); setPage('import'); setDialog(null); }} />}
  {dialog === 'settings' && <SettingsPanel state={state} command={command} close={() => setDialog(null)} />}{dialog === 'jobs' && <Jobs state={state} command={command} close={() => setDialog(null)} />}
  {dialog === 'visual' && episode && <EpisodeVisualRequirements state={state} episode={episode} command={command} close={()=>setDialog(null)}/>}
  {dialog === 'materials' && episode && <MaterialBoard episode={episode} assets={assets} command={command} close={() => setDialog(null)} add={() => { setDialog(null); setPage('import'); }} />}
  {dialog === 'export' && episode && <ExportPanel state={state} episode={episode} command={command} close={() => setDialog(null)} jobs={() => setDialog('jobs')} />}
  {dialog === 'skip-images' && episode && <Modal title="分镜图尚未完成" close={() => setDialog(null)}><div className="modal-body"><p>仍有 {shots.filter(s => !s.skipImage && !state.takes.some(t => t.id === s.approvedImageId && t.status === 'approved' && t.sourceRevision === s.revision)).length} 个镜头未选定分镜图，是否跳过并进入视频工作台？</p><div className="row modal-actions"><button onClick={() => setDialog(null)}>继续制作分镜图</button><button className="primary" onClick={() => safeAction(async () => { await enterVideo(true); setDialog(null); })}>确认跳过并进入</button></div></div></Modal>}
  {(error || notice) && <div className="notifications">{error && <div className="toast error" role="alert"><p>{error}</p><button aria-label="关闭错误" onClick={() => setError('')}>×</button></div>}{notice && <div className="toast"><p>{notice}</p><button onClick={() => setNotice('')}>×</button></div>}</div>}
  </div>;
}

function CreateProject({ command, close, created }: { command: Command; close: () => void; created: (id: string) => void }) { const [name, setName] = useState(''), [busy, setBusy] = useState(false); return <Modal title="新建项目" close={close}><form className="modal-body" onSubmit={e => { e.preventDefault(); setBusy(true); safeAction(async () => { try { const result = await command('episode.create', { name: name.trim() }) as Episode; created(typeof result === 'string' ? result : result.id); } finally { setBusy(false); } }); }}><label className="field"><span>项目名称</span><input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder="例如：精神病吸血鬼 · EP1" /></label><p className="hint">下一步添加原视频、剧本和参考资产。</p><button className="primary large full" disabled={!name.trim() || busy}>{busy ? '创建中…' : '创建并添加素材 →'}</button></form></Modal>; }
function UploadZone({ title, role, description, assets, upload, remove, disabled, accept }: { title: string; role: string; description: string; assets: Asset[]; upload: Upload; remove: (id: string) => Promise<void>; disabled: boolean; accept?: string }) { const [drag, setDrag] = useState(false); return <section className={`upload-zone ${drag ? 'drag-active' : ''}`} onDragOver={e => { e.preventDefault(); if (!disabled) setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={e => { e.preventDefault(); setDrag(false); if (!disabled) safeAction(() => upload(e.dataTransfer.files, role)); }}><div className="row spread"><h2>{title}</h2><span className="tag">{assets.length} 个文件</span></div><p>{description}</p><label className={`upload-target ${disabled ? 'disabled' : ''}`}><input aria-label={`上传${title}`} type="file" multiple accept={accept} disabled={disabled} onChange={e => { const files = Array.from(e.target.files || []); if (files.length) safeAction(() => upload(files, role)); e.target.value = ''; }} /><span className="upload-plus">＋</span><strong>点击选择，或把文件拖到这里</strong><small>支持一次添加多个文件</small></label><div className="upload-files">{assets.map(a => <div key={a.id}>{a.kind === 'image' || a.kind === 'video' ? <img src={a.kind === 'image' ? media(a.id) : thumbnail(a.id)} alt="" /> : <span>≡</span>}<span className="upload-filename">{a.name}</span><button className="text-button upload-remove" aria-label={`移除 ${a.name}`} disabled={disabled} onClick={() => safeAction(() => remove(a.id))}>移除</button></div>)}</div></section>; }
function ImportPage({ episode, assets, upload, importing, pending, start, command, hasShots, continueLegacy }: { episode: PreparedEpisode; assets: Asset[]; upload: Upload; importing: boolean; pending: boolean; start: (script?: string, skipAnalysis?: boolean) => Promise<void>; command: Command; hasShots: boolean; continueLegacy: () => void }) { const [script, setScript] = useState(episode.script), [starting, setStarting] = useState(false), [removing, setRemoving] = useState(false); const remove = async (id: string) => { setRemoving(true); try { await command('asset.remove', { id }); } finally { setRemoving(false); } }; const sources = assets.filter(a => a.role === 'source'), refs = assets.filter(a => Object.keys(assetRoles).filter(r => !['source', 'script'].includes(r)).includes(a.role)); useEffect(() => setScript(episode.script), [episode.script]); return <main className="import-page"><div className="page-title"><div><span className="eyebrow">项目准备 · 1 / 2</span><h1>上传素材</h1><p>Codex 会分析素材、自动拆镜，提取每镜首帧并写好提示词。</p></div>{hasShots && <button onClick={continueLegacy}>继续已有制作</button>}</div><div className="upload-grid"><section className="upload-zone episode-script-zone"><div className="row spread"><h2>本集剧本</h2><span className="tag">{script.trim() ? `${script.length} 字` : '待补充'}</span></div><p>{episode.script.trim() ? '已载入本集剧本，可直接修改。无需重复上传。' : '尚无分集内容，可直接粘贴或补充本集剧本。'}</p><textarea aria-label="本集剧本" rows={12} value={script} disabled={starting} onChange={e => setScript(e.target.value)} onBlur={() => { if (script !== episode.script) safeAction(() => command('episode.update', { id: episode.id, patch: { script } })); }} placeholder="暂无本集剧本，可在这里粘贴或补充人物、对白和镜头要求…" /></section><UploadZone title="原视频" role="source" description="需要改造的实拍片段，至少添加一个视频。" assets={sources} upload={upload} remove={remove} disabled={importing || starting || removing} accept="video/*" /><UploadZone title="素材" role="reference" description="人物、场景、服装、道具等参考，分类可稍后调整。" assets={refs} upload={upload} remove={remove} disabled={importing || starting || removing} accept="image/*,video/*,audio/*,.pdf,.txt,.md" /></div>{episode.preparation?.error && <p className="error-text">上次准备失败：{episode.preparation.error}</p>}<div className="import-next"><div><strong>{importing ? '素材正在导入…' : `${sources.filter(a => a.kind === 'video').length} 个原视频已就绪`}</strong><p>一次开始，自动完成整理。完成后直接进入分镜图工作台。</p></div><div className="row"><button disabled={!sources.some(a => a.kind === 'video') || importing || starting || removing} onClick={() => { setStarting(true); safeAction(async () => { try { await start(script, true); } finally { setStarting(false); } }); }}>跳过 AI 分析</button><button className="primary large" disabled={!sources.some(a => a.kind === 'video') || importing || starting || removing} onClick={() => { setStarting(true); safeAction(async () => { try { await start(script); } finally { setStarting(false); } }); }}>{starting ? '正在启动…' : '✧ Codex 自动整理 / 分析 →'}</button></div></div></main>; }
function PreparationPage({ episode, state, command, retry, skip, materials }: { episode: PreparedEpisode; state: State; command: Command; retry: () => Promise<void>; skip: () => Promise<void>; materials: () => void }) {
  const [busy, setBusy] = useState(false);
  const p = episode.preparation, job = state.jobs.find(j => j.id === p?.jobId) || [...state.jobs].reverse().find(j => j.episodeId === episode.id && j.type === 'episode.prepare');
  const paused = job?.status === 'paused', failed = !paused && (p?.status === 'failed' || job?.status === 'failed' || job?.status === 'cancelled');
  const active = job && ['queued', 'running'].includes(job.status);
  const stages = ['整理与分析素材', '识别镜头切点', '提取每镜首帧', '分析镜头与编写提示词', '准备分镜图工作台'];
  const progress = Math.min(1, Math.max(0, job?.progress || 0));
  let detail = job?.message || p?.message || '等待任务状态';
  try { const event = JSON.parse(detail); detail = event.error?.message || event.message || detail; } catch { /* Plain status text. */ }
  const action = (type: string) => safeAction(async () => { setBusy(true); try { await command(type, { id: job!.id }); } finally { setBusy(false); } });
  return <main className="prepare-page">
    <span className={`prepare-orbit ${failed ? 'failed' : ''}`}>{paused ? 'Ⅱ' : failed ? '!' : '✧'}</span>
    <span className="eyebrow">项目准备 · 2 / 2</span><h1>{paused ? '分析已暂停' : failed ? '准备暂时中断' : 'Codex 正在整理你的项目'}</h1>
    <p>{paused ? '已保留完成的分析与素材' : p?.message || '准备分析素材'}</p>
    <progress value={progress} max={1} />
    <div className={`preparation-log ${failed || /timed out|Reconnecting|失败|超时/i.test(detail) ? 'warning' : ''}`} role="status" aria-live="polite" title={detail}>
      <time>{job?.updatedAt ? new Date(job.updatedAt).toLocaleTimeString('zh-CN', { hour12: false }) : '--:--:--'}</time><span>{detail}</span>
    </div>
    <div className="preparation-controls row">{(active || paused) && <button disabled={busy} onClick={() => action(paused ? 'preparation.resume' : 'preparation.pause')}>{busy ? '正在处理…' : paused ? '恢复分析' : '暂停分析'}</button>}{(job?.status === 'queued' || paused) && !episode.analysisSkipped && <button disabled={busy} onClick={() => safeAction(async () => { setBusy(true); try { await skip(); } finally { setBusy(false); } })}>跳过 AI 分析</button>}</div>
    <div className="preparation-stages">{stages.map((stage, i) => <div key={stage} className={progress >= (i + 1) / stages.length ? 'done' : !paused && !failed && progress >= i / stages.length ? 'current' : ''}><span>{progress >= (i + 1) / stages.length ? '✓' : `0${i + 1}`}</span>{stage}</div>)}</div>
    {failed ? <><pre className="error-detail">{job?.error || p?.error || detail}</pre><button className="primary large" disabled={busy} onClick={() => safeAction(async () => { setBusy(true); try { await retry(); } finally { setBusy(false); } })}>重新整理并继续</button></> : <p className="muted">{paused ? '恢复后从保存的步骤继续，尚未完成的那次分析会重新执行。' : '完成后会自动打开分镜图工作台。只有存在疑问的镜头需要你补充说明。'}</p>}
    <button className="text-button" onClick={materials}>返回素材页</button>
  </main>;
}
function MaterialBoard({ episode, assets, command, close, add }: { episode: PreparedEpisode; assets: Asset[]; command: Command; close: () => void; add: () => void }) { return <Modal title="素材板" close={close} wide><div className="modal-body"><div className="row spread"><h3>{assets.filter(a => a.role === 'source').length} 个原视频 · {assets.filter(a => a.role === 'script').length} 份剧本 · {assets.filter(a => ['reference', 'scene', 'character', 'costume', 'prop', 'look'].includes(a.role)).length} 份参考资产</h3><button onClick={add}>添加素材 / 重新分析</button></div><p className="material-analysis">{episode.materialAnalysis || '尚无自动分析摘要；已有镜头和生成版本会继续保留。'}</p>{[['source', '原视频'], ['script', '剧本'], ['assets', '参考资产']].map(([role, title]) => <section className="material-category" key={role}><h3>{title}</h3><div className="material-assets">{assets.filter(a => role === 'assets' ? ['reference', 'scene', 'character', 'costume', 'prop', 'look'].includes(a.role) : a.role === role).map(a => <article className="material-tile" key={a.id}>{a.kind === 'image' || a.kind === 'video' ? <img src={a.kind === 'image' ? media(a.id) : thumbnail(a.id)} alt={a.name} /> : null}<div><h3>{a.name}</h3><p>{(a as Asset & { analysis?: string }).analysis || (a.kind === 'document' ? a.text?.slice(0, 300) : '') || '素材已保存，展开下方详情可调整分类。'}</p></div></article>)}</div>{role === 'script' && episode.script && <details><summary>直接粘贴的剧本</summary><pre>{episode.script}</pre></details>}</section>)}<details><summary>剧本与整集要求</summary><Field label="项目名称" value={episode.name} onSave={name => command('episode.update', { id: episode.id, patch: { name } })} /><Field label="剧本" value={episode.script} onSave={script => command('episode.update', { id: episode.id, patch: { script } })} multiline rows={8} /><Field label="历史本集制作备注" value={episode.brief} onSave={brief => command('episode.update', { id: episode.id, patch: { brief } })} multiline /><Field label="本集影调与光影基准" value={episode.look} onSave={look => command('episode.update', { id: episode.id, patch: { look } })} multiline /></details><details><summary>素材分类、预览与服务地址</summary>{assets.filter(a => Object.keys(assetRoles).includes(a.role)).map(a => <AssetDetail key={a.id} asset={a} command={command} />)}</details><details><summary>整集提示词</summary><Field label="整集提示词" value={episode.fullPrompt} multiline rows={10} onSave={fullPrompt => command('episode.update', { id: episode.id, patch: { fullPrompt } })} /><button onClick={() => safeAction(() => command('ai.episodePrompt', { episodeId: episode.id }))}>重新编写整集提示词</button></details></div></Modal>; }
function AssetDetail({ asset, command }: { asset: Asset; command: Command }) { const patch = (patch: Partial<Asset>) => command('asset.update', { id: asset.id, patch }); return <details className="asset-details"><summary>{asset.name} · {assetRoles[asset.role] || asset.role}</summary>{asset.kind === 'video' ? <video className="modal-video" controls src={media(asset.id)} /> : asset.kind === 'image' ? <img className="modal-image" src={media(asset.id)} alt={asset.name} /> : <pre>{asset.text || ''}</pre>}<Field label="名称" value={asset.name} onSave={name => patch({ name })} /><label className="field"><span>素材分类</span><select value={asset.role} onChange={e => safeAction(() => patch({ role: e.target.value }))}>{Object.entries(assetRoles).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><Field label="服务可访问的素材 URL（可选）" value={asset.remoteUrl || ''} onSave={remoteUrl => patch({ remoteUrl })} /><button className="text-button danger-text" onClick={() => { if (window.confirm(`从素材库移除「${asset.name}」？源文件会保留。`)) safeAction(() => command('asset.remove', { id: asset.id })); }}>移除素材</button></details>; }
function ExportPanel({ state, episode, command, close, jobs }: { state: State; episode: Episode; command: Command; close: () => void; jobs: () => void }) { const [audio, setAudio] = useState('original'); const segments = state.segments.filter(s => s.episodeId === episode.id), shots = state.shots.filter(s => s.episodeId === episode.id); const [scope, setScope] = useState('all'); return <Modal title="导出成片与项目" close={close}><div className="modal-body"><p className="hint">按剪辑段顺序拼接选定版本；未选定版本的段落使用实拍画面。</p><label className="field"><span>导出范围</span><select value={scope} onChange={e => setScope(e.target.value)}><option value="all">全部 {segments.length} 个剪辑段</option>{segments.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>音轨来源</span><select value={audio} onChange={e => setAudio(e.target.value)}><option value="original">实拍原声</option><option value="generated">AI 生成音轨</option></select></label><button className="primary large full" disabled={!segments.length} onClick={() => safeAction(async () => { await command('export.video', { episodeId: episode.id, audio, ...(scope !== 'all' ? { segmentIds: [scope] } : {}) }); jobs(); })}>导出视频</button><hr /><button className="full" onClick={() => safeAction(async () => { await command('export.project', { episodeId: episode.id }); jobs(); })}>导出项目数据</button><button className="full" onClick={() => downloadText(`${episode.name}-全部提示词.txt`, [episode.fullPrompt, ...shots.map(s => `${s.name}\n${s.imagePrompt}\n${s.videoPrompt}`), ...segments.map(s => `${s.name}\n${s.prompt}`)].join('\n\n'))}>下载全部提示词</button></div></Modal>; }
