import { useEffect, useState, type ReactNode } from 'react';
import type { Alignment, Clip, WorkspaceState } from '../shared/types';

export type State = WorkspaceState & { llmApiKeySet?: boolean; imageApiKeySet?: boolean; codexConnection?: { status:string; message:string; authenticated:boolean; imageAvailable:boolean; version:string; loginUrl:string; checkedAt:string }; apiKeySet?: boolean };
export type Command = (type: string, payload?: Record<string, unknown>) => Promise<unknown>;
export const media = (id?: string) => id ? `/media/${encodeURIComponent(id)}` : '';
export const thumbnail = (id?: string) => id ? `${media(id)}?thumbnail=1` : '';
export const fmt = (seconds = 0) => { const s = Math.max(0, Number.isFinite(seconds) ? seconds : 0); return `${Math.floor(s / 60).toString().padStart(2, '0')}:${Math.floor(s % 60).toString().padStart(2, '0')}.${Math.floor(s % 1 * 100).toString().padStart(2, '0')}`; };
export const duration = (clips: Clip[]) => clips.reduce((sum, clip) => sum + Math.max(0, clip.out - clip.in), 0);
export const clamp = (n: number, min: number, max: number) => Math.min(Math.max(n, min), Math.max(min, max));
export function clipAt(clips: Clip[], time: number) { let offset = 0; for (let i = 0; i < clips.length; i++) { const clip = clips[i]!; const length = clip.out - clip.in; if (time < offset + length || i === clips.length - 1) return { clip, offset, localTime: clamp(time - offset, 0, length) }; offset += length; } return undefined; }
export function mappedTime(alignments: Alignment[], source: number, fallback: number) { const a = alignments.find(a => source >= a.sourceIn && source <= a.sourceOut); if (!a) return fallback; const points = [{ source: a.sourceIn, generated: a.generatedIn }, ...a.anchors.filter(p => p.source > a.sourceIn && p.source < a.sourceOut), { source: a.sourceOut, generated: a.generatedOut }].sort((a, b) => a.source - b.source); for (let i = 1; i < points.length; i++) { const right = points[i]!, left = points[i - 1]!; if (source <= right.source) return left.generated + (source - left.source) / Math.max(.00001, right.source - left.source) * (right.generated - left.generated); } return a.generatedOut; }
export function inverseMappedTime(alignments: Alignment[], generated: number) { return mappedTime(alignments.map(a => ({ ...a, sourceIn: a.generatedIn, sourceOut: a.generatedOut, generatedIn: a.sourceIn, generatedOut: a.sourceOut, anchors: a.anchors.map(p => ({ source: p.generated, generated: p.source })) })), generated, generated); }
export function Field({ label, value, onSave, multiline = false, rows = 3, placeholder, mono = false }: { label: string; value: string; onSave: (value: string) => Promise<unknown> | void; multiline?: boolean; rows?: number; placeholder?: string; mono?: boolean }) {
  const [draft, setDraft] = useState(value); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { setDraft(value); }, [value]);
  async function save() { if (draft === value) return; setSaving(true); setError(''); try { await onSave(draft); } catch (e) { setError(String(e instanceof Error ? e.message : e)); } finally { setSaving(false); } }
  return <label className={`field ${mono ? 'mono' : ''}`}><span>{label}{saving && <small>保存中…</small>}{draft !== value && !saving && <small>离开输入框自动保存</small>}</span>{multiline ? <textarea value={draft} rows={rows} placeholder={placeholder} onChange={e => setDraft(e.target.value)} onBlur={() => void save()} /> : <input value={draft} placeholder={placeholder} onChange={e => setDraft(e.target.value)} onBlur={() => void save()} onKeyDown={e => { if (e.key === 'Enter') e.currentTarget.blur(); }} />}{error && <small className="error-text">{error}</small>}</label>;
}
export function NumberField({ label, value, min = 0, max, step = .04, onSave }: { label: string; value: number; min?: number; max?: number; step?: number; onSave: (n: number) => Promise<unknown> | void }) { const [draft, setDraft] = useState(String(value)); useEffect(() => setDraft(String(Math.round(value * 10000) / 10000)), [value]); return <label className="field"><span>{label}</span><input type="number" min={min} max={max} step={step} value={draft} onChange={e => setDraft(e.target.value)} onBlur={() => { const n = Number(draft); if (!Number.isFinite(n) || draft === '' || n < min || (max !== undefined && n > max)) { setDraft(String(value)); return; } if (n !== value) void Promise.resolve(onSave(n)).catch(() => setDraft(String(value))); }} /></label>; }
export function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="empty"><div className="empty-glyph">◇</div><strong>{title}</strong><p>{children}</p></div>; }
export function Modal({ title, children, close, wide }: { title: string; children: ReactNode; close: () => void; wide?: boolean }) { useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === 'Escape') close(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [close]); return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section role="dialog" aria-modal="true" aria-label={title} className={`modal ${wide ? 'wide' : ''}`}><header><h2>{title}</h2><button aria-label="关闭" onClick={close}>×</button></header>{children}</section></div>; }
export function downloadText(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export function safeAction(task: () => Promise<unknown>) { void task().catch(() => {}); }
