import { useRef, useState } from 'react';
import type { Shot } from '../shared/types';
import type { PreparedEpisode, Upload } from './App';
import { downloadText, Empty, Field, fmt, media, Modal, NumberField, safeAction, type Command, type State } from './common';
import { ShotRequirements } from './VisualRequirements';
import { TakeFeedback } from './Panels';

type PlannedShot = Shot & { issues?: string[]; automated?: boolean };
const firstFrame = (shot: Shot) => shot.sourceFrameId ? media(shot.sourceFrameId) : `/api/frame?assetId=${encodeURIComponent(shot.assetId)}&time=${shot.in}`;
export function ImageWorkspace({ state, episode, command, upload, importing, next, skip, ready, addMaterials }: { state: State; episode: PreparedEpisode; command: Command; upload: Upload; importing: boolean; next: () => Promise<void>; skip: () => Promise<void>; ready: boolean; addMaterials: () => void }) {
  const shots = state.shots.filter(s => s.episodeId === episode.id) as PlannedShot[], [selected, setSelected] = useState<string[]>([]), [shotId, setShotId] = useState(''), [filter, setFilter] = useState('all'), [batching, setBatching] = useState(false), [entering, setEntering] = useState(false);
  const validApproval = (s: Shot) => state.takes.find(t => t.id === s.approvedImageId && t.status === 'approved' && t.sourceRevision === s.revision);
  const shot = shots.find(s => s.id === shotId), readyCount = shots.filter(s => validApproval(s) || s.skipImage || episode.skipImages).length;
  const active = (id: string) => state.jobs.some(j => j.targetId === id && ['queued', 'running', 'waiting'].includes(j.status) && ['ai.image', 'ai.imagePrompt', 'ai.revise'].includes(j.type));
  async function batch() { setBatching(true); try { for (const id of selected) { const s = shots.find(s => s.id === id); if (s?.imagePrompt.trim() && s.confirmed && !active(id)) await command('ai.image', { shotId: id }); } setSelected([]); } finally { setBatching(false); } }
  const filtered = shots.filter(s => filter === 'all' || (filter === 'issues' ? !!s.issues?.length : filter === 'approved' ? !!validApproval(s) : !(validApproval(s) || s.skipImage || episode.skipImages)));
  return <main className="image-workspace"><div className="page-title"><div><span className="eyebrow">先确定画面，再制作视频</span><h1>分镜图工作台</h1><p>{episode.analysisSkipped || shots.every(s => s.analysisSkipped || s.facts.startsWith('已跳过 AI 分析')) ? '已跳过 AI 分析 · ' : ''}{shots.length} 个镜头 · {readyCount} 个已选定或跳过。点击画面，查看原图与候选。</p></div><div className="next-actions"><button className="primary large" disabled={!ready || entering} onClick={() => { setEntering(true); safeAction(async () => { try { await next(); } finally { setEntering(false); } }); }}>{entering ? '正在整理剪辑段…' : '进入视频工作台 →'}</button>{!ready && shots.length > 0 && <button className="text-button" disabled={entering} onClick={() => { setEntering(true); safeAction(async () => { try { await skip(); } finally { setEntering(false); } }); }}>跳过静态图，直接制作视频</button>}</div></div>
  <div className="gallery-toolbar"><div className="segmented"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>全部镜头</button><button className={filter === 'pending' ? 'active' : ''} onClick={() => setFilter('pending')}>待选定</button><button className={filter === 'approved' ? 'active' : ''} onClick={() => setFilter('approved')}>已选定</button>{shots.some(s => s.issues?.length) && <button className={filter === 'issues' ? 'active' : ''} onClick={() => setFilter('issues')}>需要补充 · {shots.filter(s => s.issues?.length).length}</button>}</div><div className="row"><button className="text-button" onClick={() => setSelected(selected.length ? [] : filtered.map(s => s.id))}>{selected.length ? '取消选择' : '选择全部'}</button>{selected.length > 0 && <button className="primary" disabled={batching || !shots.some(s => selected.includes(s.id) && s.confirmed && s.imagePrompt.trim() && !active(s.id))} onClick={() => safeAction(batch)}>{batching ? '正在提交…' : `生成所选 ${selected.length} 镜头`}</button>}</div></div>
  {shots.length ? <div className="frame-grid">{filtered.map((s, i) => { const takes = state.takes.filter(t => t.kind === 'image' && t.shotId === s.id), approved = state.assets.find(a => a.id === validApproval(s)?.assetId); return <article className={`frame-card ${selected.includes(s.id) ? 'checked' : ''}`} key={s.id}><div className="frame-card-top"><label className="check"><input aria-label={`选择 ${s.name}`} type="checkbox" checked={selected.includes(s.id)} onChange={e => setSelected(ids => e.target.checked ? [...ids, s.id] : ids.filter(id => id !== s.id))} /><span>{s.name}</span></label><span className="muted">{(s.out - s.in).toFixed(1)}s</span></div><button className="frame-image" aria-label={`查看 ${s.name}`} onClick={() => setShotId(s.id)}><img loading="lazy" src={approved ? media(approved.id) : firstFrame(s)} alt={`${s.name} ${approved ? '选定分镜图' : '实拍首帧'}`} /><span>{approved ? '已选定分镜' : '实拍首帧'}</span><b>{String(shots.indexOf(s) + 1 || i + 1).padStart(2, '0')}</b></button><div className="frame-card-bottom"><span>{active(s.id) ? '✧ 正在生成…' : s.issues?.length ? `需要补充 ${s.issues.length} 项` : approved ? '✓ 已选定' : s.skipImage || episode.skipImages ? '已跳过静态' : takes.length ? `${takes.length} 个候选 · 待选择` : '等待生成候选'}</span><button className="text-button" onClick={() => setShotId(s.id)}>{takes.length ? '比较 / 修改 →' : '查看并生成 →'}</button></div></article>; })}</div> : <div className="gallery-empty"><Empty title="尚无镜头">添加原视频并运行 Codex 自动整理，即可得到每镜首帧与提示词。</Empty><button className="primary" onClick={addMaterials}>添加素材与自动整理 →</button></div>}
  {shot && <ShotReview key={shot.id} shot={shot} state={state} command={command} upload={upload} importing={importing} busy={active(shot.id)} close={() => setShotId('')} previous={shots.indexOf(shot) > 0 ? () => setShotId(shots[shots.indexOf(shot) - 1]!.id) : undefined} next={shots.indexOf(shot) < shots.length - 1 ? () => setShotId(shots[shots.indexOf(shot) + 1]!.id) : undefined} />}
  </main>;
}
export function ShotReview({ shot, state, command, upload, importing, busy, close, previous, next }: { shot: PlannedShot; state: State; command: Command; upload: Upload; importing: boolean; busy: boolean; close: () => void; previous?: () => void; next?: () => void }) {
  const [takeId, setTakeId] = useState(''), [frameTime, setFrameTime] = useState(shot.sourceFrameTime ?? shot.in), input = useRef<HTMLInputElement>(null);
  const takes = state.takes.filter(t => t.kind === 'image' && t.shotId === shot.id).sort((a, b) => b.version - a.version), take = takes.find(t => t.id === takeId) || takes.find(t => t.id === shot.approvedImageId) || takes[0];
  const patch = (patch: Partial<PlannedShot>) => command('shot.update', { id: shot.id, patch });
  const referenceAssets = state.assets.filter(a => a.episodeId === shot.episodeId && a.kind === 'image' && !['image-candidate', 'source-frame', 'original-frame'].includes(a.role));
  return <Modal title={`${shot.name} · 分镜图`} close={close} wide><div className="modal-body shot-review"><div className="row spread review-navigation"><span>{fmt(shot.in)} — {fmt(shot.out)} · {shot.scene || '实拍镜头'}</span><div className="row"><button disabled={!previous} onClick={previous}>← 上一镜</button><button disabled={!next} onClick={next}>下一镜 →</button></div></div>{!!shot.issues?.length && <section className="issues-panel"><h3>这几处需要你补充</h3><ul>{shot.issues.map(issue => <li key={issue}>{issue}</li>)}</ul><Field label="补充事实与修正" value={shot.facts} onSave={facts => patch({ facts })} multiline /><button onClick={() => safeAction(() => patch({ issues: [], confirmed: true }))}>已核对，解除疑问</button></section>}
  <div className="image-compare"><figure><figcaption>实拍首帧 · 生成依据</figcaption><div><img src={firstFrame(shot)} alt={`${shot.name} 实拍首帧`} /></div></figure><figure><figcaption>{take ? `候选 V${take.version} · ${take.status === 'approved' ? '已选定' : take.status === 'rejected' ? '已退回' : '待选择'}` : '生成候选'}</figcaption><div>{take ? <img src={media(take.assetId)} alt={`${shot.name} 候选 V${take.version}`} /> : <Empty title="还没有候选图">提示词已准备好，点击生成即可开始。</Empty>}</div></figure></div>
  <ShotRequirements state={state} shot={shot} command={command} sceneControls/>
  <div className="review-primary"><div className="row wrap"><button className="primary large" disabled={busy || !shot.imagePrompt.trim() || !shot.confirmed} onClick={() => safeAction(() => command('ai.image', { shotId: shot.id }))}>{busy ? '正在生成…' : '✧ 生成新候选'}</button><button disabled={importing} onClick={() => input.current?.click()}>{importing ? '上传中…' : '上传候选图'}</button><input ref={input} aria-label="上传候选图" type="file" accept="image/*" multiple hidden onChange={e => { const files = Array.from(e.target.files || []); if (files.length) safeAction(() => upload(files, 'image-candidate', { shotId: shot.id })); e.target.value = ''; }} /></div>{take && <button className={`large ${shot.approvedImageId === take.id ? 'secondary' : 'primary'}`} onClick={() => safeAction(() => command('take.approve', { id: take.id, scope: 'shot' }))}>{shot.approvedImageId === take.id ? '✓ 已选为本镜分镜图' : '选定此图 →'}</button>}</div>
  {!shot.confirmed && !shot.issues?.length && <div className="issues-panel"><p>此镜头来自已有工程，尚未核对分析结果。</p><button onClick={() => safeAction(() => patch({ confirmed: true }))}>已核对现有镜头事实</button></div>}
  <div className="take-strip">{takes.map(t => <button className={`take-tile ${take?.id === t.id ? 'selected' : ''}`} key={t.id} onClick={() => setTakeId(t.id)}><div><img src={media(t.assetId)} alt={`候选 V${t.version}`} /><span>V{t.version}</span></div><footer><span>{t.status === 'approved' ? '已选定' : t.status === 'rejected' ? '已退回' : '待选择'}</span></footer></button>)}</div>{take && take.sourceRevision !== shot.revision && <p className="hint">此候选生成后镜头要求有过修改，请按最新要求复核。</p>}
  {take && <details className="review-details"><summary>修改当前候选</summary><TakeFeedback key={take.id} take={take} command={command} /><button className="primary" disabled={busy || !shot.imagePrompt.trim()} onClick={() => safeAction(() => command('ai.image', { shotId: shot.id, takeId: take.id, prompt: shot.imagePrompt }))}>按最新提示词修改此图</button><button className="text-button danger-text" onClick={() => safeAction(() => command('take.reject', { id: take.id }))}>退回此候选</button><button className="text-button" onClick={() => safeAction(() => command('take.approve', { id: take.id, scope: 'look' }))}>设为同场景影调参考</button></details>}
  <details className="review-details"><summary>提示词与参考资产（高级）</summary><Field label="静态提示词" value={shot.imagePrompt} onSave={imagePrompt => patch({ imagePrompt })} multiline rows={8} /><div className="row wrap"><button disabled={busy} onClick={() => safeAction(() => command('ai.imagePrompt', { shotId: shot.id }))}>Codex 重新编写</button><button onClick={() => downloadText(`${shot.name}-静态提示词.txt`, shot.imagePrompt)}>下载提示词</button></div><h3 className="spaced-title">参考资产</h3><div className="reference-list">{referenceAssets.map(a => <label className={`reference-item ${shot.referenceIds.includes(a.id) ? 'selected' : ''}`} key={a.id}><input type="checkbox" checked={shot.referenceIds.includes(a.id)} onChange={e => safeAction(() => patch({ referenceIds: e.target.checked ? [...shot.referenceIds, a.id] : shot.referenceIds.filter(id => id !== a.id) }))} /><img src={media(a.id)} alt="" /><span>{a.name}</span></label>)}</div>{take && <details><summary>当前版本实际提示词</summary><pre>{take.prompt}</pre></details>}</details>
  <details className="review-details"><summary>镜头分析与更换原帧（高级）</summary><Field label="实拍事实" value={shot.facts} onSave={facts => patch({ facts })} multiline /><Field label="改造计划" value={shot.plan} onSave={plan => patch({ plan })} multiline /><Field label="视频提示词" value={shot.videoPrompt} onSave={videoPrompt => patch({ videoPrompt })} multiline /><NumberField label="更换原帧时间 / 秒" value={frameTime} min={shot.in} max={Math.max(shot.in, shot.out - .04)} onSave={setFrameTime} /><button onClick={() => safeAction(() => command('image.capture', { shotId: shot.id, time: frameTime }))}>使用这一帧</button><label className="check"><input type="checkbox" checked={shot.skipImage} onChange={e => safeAction(() => patch({ skipImage: e.target.checked }))} />此镜跳过静态图</label></details>
  </div></Modal>;
}
