import { useEffect, useState } from 'react';
import type { Alignment, Clip, Job, Settings, Take } from '../shared/types';
import { Field, fmt, media, Modal, NumberField, safeAction, type Command, type State } from './common';

const statusLabels: Record<string, string> = { paused: '已暂停', queued: '排队中', running: '运行中', waiting: '等待远程任务', succeeded: '已完成', failed: '失败', cancelled: '已取消', uncertain: '状态待核实' };
const jobLabels: Record<string, string> = { 'episode.prepare': '项目自动整理', 'episode.group': '自动组段', 'shots.detect': '镜头识别', 'ai.analyze': 'AI 分析', 'ai.episodePrompt': '整集提示词', 'ai.imagePrompt': '静态提示词', 'ai.image': '图像生成', 'ai.revise': '反馈返修', 'ai.segmentPrompt': '剪辑段提示词', 'segment.prepare': '准备实拍片段', 'segment.generate': '视频生成', 'take.autoAlign': '自动对齐', 'export.video': '视频导出', 'export.project': '项目导出', 'codex.check': 'Codex 检查' };
function JobRow({ job, state, command }: { job: Job; state: State; command: Command }) { const [remote, setRemote] = useState(job.remoteId || ''); const asset = state.assets.find(a => a.id === job.resultId); return <article className={`job-card ${job.status}`}><div className="row spread"><strong>{job.type === 'project.analyze' ? '总剧本分析与分集' : jobLabels[job.type] || job.type}</strong><span className={`tag ${job.status === 'failed' ? 'danger' : job.status === 'succeeded' ? 'success' : ''}`}>{statusLabels[job.status] || job.status}</span></div><p>{job.message || '等待任务开始'}</p>{['running', 'queued', 'waiting'].includes(job.status) && <progress value={job.progress} max={1} />}<div className="job-meta"><span>{new Date(job.createdAt).toLocaleString('zh-CN')}</span><span>{state.episodes.find(e => e.id === job.episodeId)?.name || '工作台'}</span></div>{job.error && <pre className="error-detail">{job.error}</pre>}{job.remoteId && <code className="remote-id">远程 ID：{job.remoteId}</code>}<div className="row wrap">{['queued', 'running', 'waiting', 'uncertain'].includes(job.status) && <button onClick={() => safeAction(() => command('job.cancel', { id: job.id }))}>取消任务</button>}{job.status === 'paused' && <button onClick={() => safeAction(() => command('preparation.resume', { id: job.id }))}>恢复分析</button>}{['failed', 'cancelled'].includes(job.status) && <button onClick={() => safeAction(() => command('job.retry', { id: job.id }))}>重试任务</button>}{['uncertain', 'failed', 'waiting'].includes(job.status) && (job.type === 'segment.generate' || job.remoteId) && <><input aria-label="远程任务 ID" className="remote-input" value={remote} onChange={e => setRemote(e.target.value)} placeholder="远程任务 ID" /><button disabled={!remote.trim()} onClick={() => safeAction(() => command('job.resume', { id: job.id, remoteId: remote.trim() }))}>恢复查询</button></>}{job.status === 'succeeded' && asset && <a className="button" href={media(asset.id)} download={asset.name}>下载产物 ↗</a>}</div></article>; }
export function Jobs({ state, command, close }: { state: State; command: Command; close: () => void }) { const [filter, setFilter] = useState('all'); const jobs = [...state.jobs].reverse().filter(j => filter === 'all' || (filter === 'active' ? ['queued', 'running', 'waiting', 'uncertain'].includes(j.status) : j.status === 'failed')); return <Modal title="任务队列" close={close}><div className="modal-body"><div className="segmented"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>全部 {state.jobs.length}</button><button className={filter === 'active' ? 'active' : ''} onClick={() => setFilter('active')}>进行中</button><button className={filter === 'failed' ? 'active' : ''} onClick={() => setFilter('failed')}>失败</button></div><p className="hint">本地任务与远程任务状态会自动保存。状态待核实时，可用远程任务 ID 恢复查询，避免重复提交。</p><div className="job-list">{jobs.length ? jobs.map(job => <JobRow key={job.id} job={job} state={state} command={command} />) : <p className="muted">当前筛选下没有任务。</p>}</div></div></Modal>; }

export function SettingsPanel({ state, command, close }: { state: State; command: Command; close: () => void }) {
  const [draft, setDraft] = useState<Settings>({ ...state.settings, llmProvider:state.settings.llmProvider||'codex', imageProvider:state.settings.imageProvider||'codex', apiKey: '', llmApiKey:'', imageApiKey:'' }), [result, setResult] = useState(''), [saving, setSaving] = useState(false), [saved, setSaved] = useState(false);
  const [section, setSection] = useState<'software' | 'api'>('software');
  const [apiTab, setApiTab] = useState<'llm' | 'image' | 'video'>('llm');
  const [choosingFolder,setChoosingFolder]=useState(false);
  const [secretsLoading, setSecretsLoading] = useState(true), [secretsError, setSecretsError] = useState('');
  const loadSecrets = async () => {
    setSecretsLoading(true);
    setSecretsError('');
    try {
      const value = await command('settings.secrets');
      const secrets = value as Pick<Settings,'apiKey'|'llmApiKey'|'imageApiKey'>;
      setDraft(current => ({ ...current, apiKey: current.apiKey || secrets.apiKey || '', llmApiKey: current.llmApiKey || secrets.llmApiKey || '', imageApiKey: current.imageApiKey || secrets.imageApiKey || '' }));
    } catch (error) {
      setSecretsError(error instanceof Error ? error.message : '已保存的 API 设置读取失败');
    } finally {
      setSecretsLoading(false);
    }
  };
  useEffect(() => { void loadSecrets(); }, []);
  const folderField=(kind:'storage'|'export',label:string)=>{const key=kind==='storage'?'storageDir':'exportDir';const value=draft[key]||(kind==='storage'?state.settings.dataDir:`${draft.storageDir||state.settings.dataDir}/exports`);return <div className="field"><span>{label}</span><div className="folder-picker-row"><output aria-label={label} title={value}>{value}</output><button disabled={choosingFolder||saving} onClick={()=>safeAction(async()=>{setChoosingFolder(true);try{const selected=await command('settings.chooseFolder',{kind});if(typeof selected==='string'&&selected){setDraft(d=>({...d,[key]:selected}));setSaved(false);}}finally{setChoosingFolder(false);}})}>选择文件夹</button></div></div>;};
  const input = (key: keyof Settings, label: string, type = 'text') => <label className="field"><span>{label}</span><input type={type} value={String(draft[key] ?? '')} onChange={e => { setDraft(d => ({ ...d, [key]: type === 'number' ? Number(e.target.value) : e.target.value })); setSaved(false); }} autoComplete="off" /></label>;
  const secretInput = (key: 'apiKey'|'llmApiKey'|'imageApiKey', label: string, configured: boolean) => {
    if (secretsLoading) return <div className="field"><span>{label}</span><output className="settings-secret-status">正在读取已保存设置…</output></div>;
    if (secretsError && configured && !String(draft[key] || '')) return <div className="field"><span>{label}</span><div className="settings-secret-error"><output>已配置，但读取失败</output><button type="button" onClick={() => void loadSecrets()}>重试</button></div><small className="error-text">{secretsError}</small></div>;
    return input(key, label);
  };
  async function save() { setSaving(true); try { const { apiKey,llmApiKey,imageApiKey, ...rest } = draft; await command('settings.update', { patch: { ...rest, ...(apiKey ? { apiKey } : {}), ...(llmApiKey ? {llmApiKey} : {}), ...(imageApiKey ? {imageApiKey} : {}) } }); setSaved(true); } finally { setSaving(false); } }
  const [connection, setConnection] = useState<State['codexConnection']>(state.codexConnection);
  const [connecting, setConnecting] = useState(false);
  const [testingApi, setTestingApi] = useState(false), [apiTestResult, setApiTestResult] = useState('');
  useEffect(() => { if(state.codexConnection)setConnection(state.codexConnection); },[state.codexConnection]);
  useEffect(() => { let live=true; void command('codex.connection.status').then(value=>{if(live)setConnection(value as State['codexConnection']);}).catch(()=>{});return()=>{live=false;}; },[]);
  const checkCodex = () => safeAction(async () => { setConnecting(true); try { await save(); setConnection(await command('codex.connection.connect') as State['codexConnection']); } finally {setConnecting(false);} });
  const checkApi = (kind:'llm'|'image') => safeAction(async () => { setTestingApi(true); setApiTestResult(''); try { await save(); const value=await command('settings.apiTest',{kind}) as {message:string}; setApiTestResult(value.message); } catch(error) { setApiTestResult(error instanceof Error?error.message:String(error)); } finally {setTestingApi(false);} });
  const [models,setModels]=useState<Array<{model:string;displayName:string;isDefault:boolean}>>([]),[modelsLoading,setModelsLoading]=useState(false),[modelsError,setModelsError]=useState('');
  const loadModels=async()=>{setModelsLoading(true);setModelsError('');try{const value=await command('codex.models');setModels(value as typeof models);}catch{setModelsError('模型列表加载失败，请点击刷新重试。');}finally{setModelsLoading(false);}};
  useEffect(()=>{if(section==='api'&&apiTab==='llm'&&draft.llmProvider==='codex')void loadModels();},[section,apiTab,draft.llmProvider,connection?.authenticated]);
  const connectionBusy=connecting||['connecting','waiting_login','testing'].includes(connection?.status||'');
  const mode = (key:'llmProvider'|'imageProvider') => <div className="segmented provider-switch" aria-label={key==='llmProvider'?'LLM 接入模式':'生图接入模式'}>{([['codex','Codex'],['custom','自定义 API']] as const).map(([value,label])=><button key={value} aria-pressed={draft[key]===value} className={draft[key]===value?'active':''} onClick={()=>{setDraft(d=>({...d,[key]:value}));setSaved(false);}}>{label}</button>)}</div>;
  const customFields = (kind:'llm'|'image') => <>
    
    {input(kind==='llm'?'llmApiBaseUrl':'imageApiBaseUrl','完整 Base URL','url')}
    {secretInput(kind==='llm'?'llmApiKey':'imageApiKey',`API Key · ${(kind==='llm'?state.llmApiKeySet:state.imageApiKeySet)?'已配置':'未配置'}`,Boolean(kind==='llm'?state.llmApiKeySet:state.imageApiKeySet))}
    {input(kind==='llm'?'llmApiModel':'imageApiModel','模型名称')}
  </>;
  const currentProvider = apiTab==='llm' ? draft.llmProvider : apiTab==='image' ? draft.imageProvider : 'custom';
  const showCodexConnection = section==='api' && apiTab!=='video' && currentProvider==='codex';
  const showCustomConnection = section==='api' && apiTab!=='video' && currentProvider==='custom';
  return <Modal title="设置" close={close} wide><div className="settings-panel">
    <nav className="settings-navigation" aria-label="设置分类">
      <button className={section === 'software' ? 'active' : ''} aria-pressed={section === 'software'} onClick={() => setSection('software')}>软件设置</button>
      <button className={section === 'api' ? 'active' : ''} aria-pressed={section === 'api'} onClick={() => setSection('api')}>API 设置</button>
    </nav>
    <div className="settings-main">
      {showCodexConnection && <section className="codex-connection compact"><div className="row spread"><div><strong>Codex</strong><p className={connection?.status==='failed'?'error-text':'hint'} role="status">{connection?.authenticated?'已登录':'未登录'} · {connection?.status==='connected'?'连接成功 · 真实模型请求已返回':connection?.message||'尚未连接'}</p></div><button className="primary" disabled={connectionBusy||saving} onClick={checkCodex}>{connectionBusy?'连接中…':connection?.authenticated?'检测连接':'登录并连接'}</button></div>{connection?.loginUrl && <a className="button" href={connection.loginUrl} target="_blank" rel="noreferrer">打开登录页面</a>}{connectionBusy&&<button className="text-button" onClick={()=>safeAction(async()=>{setConnection(await command('codex.connection.cancel') as State['codexConnection']);})}>停止连接</button>}</section>}
      {showCustomConnection && <section className="codex-connection compact"><div className="row spread"><div><strong>{apiTab==='llm'?'LLM API':'生图 API'}</strong><p className={apiTestResult&&!apiTestResult.includes('成功')?'error-text':'hint'} role="status">{apiTestResult||'尚未测试'}</p></div><button className="primary" disabled={testingApi||saving} onClick={()=>checkApi(apiTab as 'llm'|'image')}>{testingApi?'测试中…':`测试${apiTab==='llm'?' LLM':'生图'} API`}</button></div></section>}

      {section === 'api' && <nav className="segmented settings-api-tabs" aria-label="API 分类">
        {([['llm', 'LLM'], ['image', '生图'], ['video', '生视频']] as const).map(([key, label]) => <button key={key} className={apiTab === key ? 'active' : ''} aria-pressed={apiTab === key} onClick={() => setApiTab(key)}>{label}</button>)}
      </nav>}
      <div className="settings-content">
        {section === 'software' && <section><h3>软件设置</h3>
          
          {folderField('storage','数据目录')}{folderField('export','导出目录')}
        </section>}
        {section === 'api' && apiTab === 'llm' && <section><h3>LLM</h3>{mode('llmProvider')}
          {draft.llmProvider==='codex'?<div className="field"><label htmlFor="codex-model-select">模型</label><div className="model-select-row"><select id="codex-model-select" value={draft.codexModel} disabled={modelsLoading} onChange={e=>{setDraft(d=>({...d,codexModel:e.target.value}));setSaved(false);}}><option value="">自动选择{models.find(m=>m.isDefault)?`（${models.find(m=>m.isDefault)!.displayName}）`:''}</option>{draft.codexModel&&!models.some(m=>m.model===draft.codexModel)&&<option value={draft.codexModel}>{draft.codexModel}（当前配置，未在列表中）</option>}{models.map(m=><option key={m.model} value={m.model}>{m.displayName}</option>)}</select><button disabled={modelsLoading} onClick={()=>void loadModels()}>{modelsLoading?'加载中…':'刷新'}</button></div>{modelsError&&<small className="error-text">{modelsError}</small>}</div>:customFields('llm')}

        </section>}
        {section === 'api' && apiTab === 'image' && <section><h3>生图</h3>{mode('imageProvider')}
          {draft.imageProvider==='custom' && customFields('image')}
        </section>}
        {section === 'api' && apiTab === 'video' && <section><h3>生视频</h3>{input('apiBaseUrl', 'API Base URL', 'url')}{secretInput('apiKey', `API Key · ${state.apiKeySet ? '已配置' : '未配置'}`, Boolean(state.apiKeySet))}{input('videoModel', '模型')}</section>}
      </div>
      <footer className="settings-footer"><button className="primary" disabled={saving||secretsLoading} onClick={() => safeAction(save)}>{saving ? '保存中…' : secretsLoading ? '读取设置…' : saved ? '已保存 ✓' : '保存设置'}</button></footer>
      {result && <pre className="connection-result" role="status">{result}</pre>}
    </div>
  </div></Modal>;
}

export function AlignmentEditor({ take, command, sourceClips = [], generatedDuration }: { take: Take; command: Command; sourceClips?: Clip[]; generatedDuration?: number }) { const update = (index: number, patch: Partial<Alignment>) => command('take.align', { id: take.id, alignments: take.alignments.map((a, i) => { if (i !== index) return a; const next = { ...a, ...patch }; if (!patch.anchors && ['sourceIn', 'sourceOut', 'generatedIn', 'generatedOut'].some(k => k in patch)) next.anchors = a.anchors.map(p => ({ source: p.source === a.sourceIn ? next.sourceIn : p.source === a.sourceOut ? next.sourceOut : p.source, generated: p.generated === a.generatedIn ? next.generatedIn : p.generated === a.generatedOut ? next.generatedOut : p.generated })).filter(p => p.source >= next.sourceIn && p.source <= next.sourceOut && p.generated >= next.generatedIn && p.generated <= next.generatedOut); next.anchors.sort((left, right) => left.source - right.source); return next; }) });
  const addAnchor = (index: number, a: Alignment) => { const points = [{ source: a.sourceIn, generated: a.generatedIn }, ...a.anchors.filter(p => p.source > a.sourceIn && p.source < a.sourceOut), { source: a.sourceOut, generated: a.generatedOut }].sort((p, q) => p.source - q.source); let left = points[0]!, right = points[1]!; for (let i = 1; i < points.length; i++) if (points[i]!.source - points[i - 1]!.source > right.source - left.source) { left = points[i - 1]!; right = points[i]!; } return update(index, { anchors: [...a.anchors, { source: (left.source + right.source) / 2, generated: (left.generated + right.generated) / 2 }], confirmed: false }); };
  const manual = () => { const clips = take.sourceClips?.length ? take.sourceClips : sourceClips; const sourceTotal = clips.reduce((sum, c) => sum + c.out - c.in, 0), scale = (generatedDuration || sourceTotal) / Math.max(.001, sourceTotal); let offset = 0; const next = [...take.alignments]; for (const clip of clips) { const start = offset; offset += clip.out - clip.in; if (!next.some(a => a.shotId === clip.shotId && Math.abs(a.sourceIn - start) < .001)) next.push({ shotId: clip.shotId, sourceIn: start, sourceOut: offset, generatedIn: start * scale, generatedOut: offset * scale, confidence: 0, confirmed: false, anchors: [] }); } return command('take.align', { id: take.id, alignments: next.sort((a,b) => a.sourceIn-b.sourceIn) }); };
  return <section className="property-section"><div className="row spread"><h3>逐镜映射</h3><button onClick={() => safeAction(() => command('take.autoAlign', { id: take.id }))}>自动对齐</button></div><button className="full" disabled={!(take.sourceClips?.length || sourceClips.length)} onClick={() => safeAction(manual)}>手动建立 / 补齐镜头映射</button><p className="hint">源时间为剪辑段累计时间。锚点在区间内做分段线性映射；确认后用于双屏比较。</p>{!take.alignments.length && <p className="muted">先运行自动对齐，再校正边界和锚点。</p>}{take.alignments.map((a, index) => <div className="alignment" key={`${take.id}-${index}`}><div className="row spread"><strong>镜头 {index + 1}</strong><span className={`tag ${a.confirmed ? 'success' : a.confidence < .6 ? 'warning' : ''}`}>{a.confirmed ? '已确认' : `置信度 ${Math.round(a.confidence * 100)}%`}</span></div><div className="form-grid"><NumberField label="源入点 s" value={a.sourceIn} max={a.sourceOut} onSave={n => update(index, { sourceIn: n, confirmed: false })} /><NumberField label="源出点 s" value={a.sourceOut} min={a.sourceIn} onSave={n => update(index, { sourceOut: n, confirmed: false })} /><NumberField label="生成入点 s" value={a.generatedIn} max={a.generatedOut} onSave={n => update(index, { generatedIn: n, confirmed: false })} /><NumberField label="生成出点 s" value={a.generatedOut} min={a.generatedIn} onSave={n => update(index, { generatedOut: n, confirmed: false })} /></div>{a.anchors.map((anchor, ai) => <div className="anchor-row" key={ai}><NumberField label="源锚点 s" value={anchor.source} min={a.sourceIn} max={a.sourceOut} onSave={n => update(index, { anchors: a.anchors.map((p, i) => i === ai ? { ...p, source: n } : p), confirmed: false })} /><span>→</span><NumberField label="生成锚点 s" value={anchor.generated} min={a.generatedIn} max={a.generatedOut} onSave={n => update(index, { anchors: a.anchors.map((p, i) => i === ai ? { ...p, generated: n } : p), confirmed: false })} /><button title="删除锚点" onClick={() => safeAction(() => update(index, { anchors: a.anchors.filter((_, i) => i !== ai), confirmed: false }))}>×</button></div>)}<div className="row wrap"><button onClick={() => safeAction(() => addAnchor(index, a))}>＋ 锚点</button><button className={a.confirmed ? 'success-text' : ''} onClick={() => safeAction(() => update(index, { confirmed: !a.confirmed }))}>{a.confirmed ? '撤销确认' : '确认映射'}</button><button className="danger-text" onClick={() => safeAction(() => command('take.align', { id: take.id, alignments: take.alignments.filter((_, i) => i !== index) }))}>移除映射</button></div></div>)}</section>; }

export function TakeFeedback({ take, command }: { take: Take; command: Command }) { const [feedback, setFeedback] = useState(take.feedback || ''); return <section className="property-section" key={take.id}><h3>反馈与返修</h3><label className="field"><span>本版本反馈</span><textarea rows={4} value={feedback} onChange={e => setFeedback(e.target.value)} placeholder="说明哪一秒、哪个对象，以及期望如何修正。" /></label><div className="row wrap"><button disabled={!feedback.trim()} onClick={() => safeAction(() => command('take.feedback', { id: take.id, feedback }))}>保存反馈</button><button className="primary" disabled={!feedback.trim()} onClick={() => safeAction(() => command('ai.revise', { takeId: take.id, feedback }))}>根据反馈修订提示词</button></div><p className="hint">AI 将结合反馈修订提示词。请检查修订结果，再点击生成创建新候选；当前版本会保留。</p></section>; }

export function ReviewPanel({ state, take, time, setTime, command }: { state: State; take?: Take; time: number; setTime: (time: number) => void; command: Command }) { const [text, setText] = useState(''), [reviewTime, setReviewTime] = useState<number | null>(null); if (!take) return <div className="property-section"><p className="muted">选择一个候选版本后可审片、批注与返修。</p></div>; const reviews = state.reviews.filter(r => r.takeId === take.id).sort((a, b) => a.time - b.time); return <><section className="property-section"><h3>时间码批注</h3><NumberField label="生成视频时间 / 秒" value={reviewTime ?? time} onSave={setReviewTime} /><button className="text-button" onClick={() => setReviewTime(time)}>使用当前比较时间 {fmt(time)}</button><textarea aria-label="审片批注" rows={3} value={text} onChange={e => setText(e.target.value)} placeholder="记录身份、动作、接触、镜头运动或画面问题…" /><button className="primary full" disabled={!text.trim()} onClick={() => safeAction(async () => { await command('review.create', { takeId: take.id, time: reviewTime ?? time, text }); setText(''); setReviewTime(null); })}>添加批注</button><div className="review-list">{reviews.map(r => <article className="review-card" key={r.id}><div className="row spread"><button className="time-link" onClick={() => setTime(r.time)}>{fmt(r.time)}</button><button title="删除批注" onClick={() => safeAction(() => command('review.delete', { id: r.id }))}>×</button></div><p>{r.text}</p></article>)}</div>{!reviews.length && <p className="hint">暂无批注。移动播放头后记录具体问题。</p>}</section>{take.kind === 'video' && <section className="property-section"><h3>成片裁剪</h3><p className="hint">只影响最终导出的选定版本，保留完整生成素材与审片记录。</p><div className="form-grid"><NumberField label="成片入点 / 秒" value={take.exportIn ?? 0} max={(take.exportOut ?? state.assets.find(a => a.id === take.assetId)?.duration ?? 1) - .04} onSave={n => command('take.trim', { id: take.id, in: n })} /><NumberField label="成片出点 / 秒" value={take.exportOut ?? state.assets.find(a => a.id === take.assetId)?.duration ?? 0} min={(take.exportIn ?? 0) + .04} max={state.assets.find(a => a.id === take.assetId)?.duration} onSave={n => command('take.trim', { id: take.id, out: n })} /></div></section>}<TakeFeedback key={take.id} take={take} command={command} />{take.kind === 'video' && <AlignmentEditor take={take} command={command} sourceClips={state.segments.find(s => s.id === take.segmentId)?.clips} generatedDuration={state.assets.find(a => a.id === take.assetId)?.duration} />}</>; }
