import { useState } from 'react';
import type { Episode } from '../shared/types';
import { Field, Modal, safeAction, type Command, type State } from './common';

export function Projects({ state, command, selected, select, open }: { state: State; command: Command; selected: string; select: (id:string)=>void; open:(ep:Episode)=>void }) {
 const [create,setCreate]=useState(false),[add,setAdd]=useState(false);
 const project=state.projects?.find(p=>p.id===selected);
 const episodes=state.episodes.filter(e=>project?e.projectId===project.id:!e.projectId);
 const job=state.jobs.filter(j=>j.type==='project.analyze'&&j.targetId===project?.id).at(-1);
 const busy=!!job&&['queued','running','waiting'].includes(job.status);
 return <main className={`projects-page ${project ? 'project-detail-page' : ''}`}>
 <div className="page-title"><div><span className="eyebrow">{project?'按集组织制作':'你的创作空间'}</span><h1>{project?.name||'项目'}</h1><p>{project?'每一集独立管理原视频、资产与制作进度。':'先建立大项目，上传总剧本，再按集制作。'}</p></div><div className="row">{project?<><button onClick={()=>select('')}>返回大项目</button><button className="primary large" onClick={()=>setAdd(true)}>＋ 添加集</button></>:<button className="primary large" onClick={()=>setCreate(true)}>＋ 新建大项目</button>}</div></div>
 {!project&&<div className="project-grid">{state.projects?.map(p=><button className="project-card parent-project" key={p.id} onClick={()=>select(p.id)}><h2>{p.name}</h2><p>{state.episodes.filter(e=>e.projectId===p.id).length} 集</p><span>打开集列表 →</span></button>)}</div>}
 <div className={project ? "project-columns" : undefined}>
 {project&&<><section className="project-script-summary"><section className="project-visual-settings"><h3>全项目风格与质感</h3><Field label="统一画面风格与质感" value={project.visualStyle||''} multiline rows={3} onSave={visualStyle=>command('project.update',{id:project.id,patch:{visualStyle}})}/><p className="hint">所有集共用。具体影调、光影按集与场景设置，单镜要求在生图和视频制作时填写。</p></section><div className="row spread"><h3>总剧本 · 初步分析</h3><button disabled={busy} onClick={()=>safeAction(()=>command('project.analyze',{id:project.id}))}>{busy?'Codex 分析中…':'重新识别集数'}</button></div>{busy&&<p role="status">{job?.message} 完成后集列表会自动更新，也可先手动添加集。</p>}{job?.status==='failed'&&<p className="error-text">分析失败：{job.error}。可以重试，或手动添加集。</p>}<p className="material-analysis">{project.summary||(!busy?'尚无分析结果。':'')}</p><details><summary>查看完整总剧本</summary><pre>{project.script}</pre></details></section></>}
 {(project||episodes.length>0)&&<section className="episode-list"><h2>{project?'集列表':'未归组的已有集'}</h2><div className="episode-list-scroll" tabIndex={0} aria-label="集列表滚动区域">{episodes.map((ep,i)=>{const sources=state.assets.filter(a=>a.episodeId===ep.id&&a.role==='source');const epShots=state.shots.filter(s=>s.episodeId===ep.id);const ready=ep.preparation?.status==='ready'||epShots.length>0&&epShots.every(s=>s.sourceFrameId&&s.facts.startsWith('已跳过 AI 分析'))||!ep.workflowVersion&&epShots.length>0;return <article className="episode-row" key={ep.id}><span className="episode-index">{String(i+1).padStart(2,'0')}</span><div><h3>{ep.name}</h3><p>{sources.length} 个原视频 · {state.assets.filter(a=>a.episodeId===ep.id&&a.role!=='source'&&a.role!=='script'&&!a.role.includes('candidate')).length} 份素材</p></div><span className="muted">{ep.preparation?.status==='running'?'正在整理':ready?'制作中':sources.length?'待分析':'待上传素材'}</span><button className="primary" onClick={()=>open(ep)}>{ready?'继续制作 →':sources.length?'继续准备 →':'上传本集素材 →'}</button></article>})}{!episodes.length&&<p className="hint">{busy?'正在识别剧本中的集数…':'尚无集，请添加集并上传本集原视频和资产。'}</p>}</div></section>}
 </div>
 {create&&<CreateMain command={command} close={()=>setCreate(false)} done={id=>{select(id);setCreate(false);}}/>}
 {add&&project&&<AddEpisode projectId={project.id} command={command} close={()=>setAdd(false)} done={ep=>{setAdd(false);open(ep);}}/>}
 </main>;
}
function CreateMain({command,close,done}:{command:Command;close:()=>void;done:(id:string)=>void}){
 const [name,setName]=useState(''),[script,setScript]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <Modal title="新建大项目" close={close}><form className="modal-body" onSubmit={e=>{e.preventDefault();setBusy(true);void command('project.create',{name,script}).then((p:any)=>done(p.id)).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label className="field"><span>大项目名称</span><input required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>上传总剧本</span><input type="file" accept=".txt,.md,.docx,.pdf,.json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');const form=new FormData();form.append('file',file);void fetch('/api/script-text',{method:'POST',body:form}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setScript(d.script);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}/></label><label className="field"><span>总剧本内容（可直接粘贴）</span><textarea aria-label="总剧本内容（可直接粘贴）" rows={9} required value={script} onChange={e=>setScript(e.target.value)}/></label><p className="hint">创建后 Codex 自动初步分析并识别集数。各集素材随后单独上传。</p>{error&&<p role="alert" className="error-text">{error}</p>}<button className="primary large full" disabled={busy||!name.trim()||!script.trim()}>{busy?'处理中…':'创建并分析总剧本 →'}</button></form></Modal>;
}
function AddEpisode({projectId,command,close,done}:{projectId:string;command:Command;close:()=>void;done:(ep:Episode)=>void}){
 const [name,setName]=useState(''),[sources,setSources]=useState<File[]>([]),[refs,setRefs]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState<Episode>();
 async function save(){setBusy(true);setError('');try{const ep=created||await command('episode.create',{projectId,name}) as Episode;setCreated(ep);for(const [role,files,setFiles] of [['source',sources,setSources],['reference',refs,setRefs]] as const){if(!files.length)continue;const form=new FormData();form.append('episodeId',ep.id);form.append('role',role);files.forEach(f=>form.append('files',f));const r=await fetch('/api/import',{method:'POST',body:form});const d=await r.json();if(!r.ok)throw Error(d.error);setFiles([]);if(d.errors?.length)throw Error(d.errors.join('\n')+'；已成功文件保留，剩余素材可在本集页面补充。');}done(ep);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <Modal title="添加集与素材" close={close}><form className="modal-body" onSubmit={e=>{e.preventDefault();void save();}}><label className="field"><span>集名称</span><input required disabled={!!created} placeholder="例如：第 3 集" value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>本集原视频（必选）</span><input type="file" accept="video/*" multiple disabled={busy} onChange={e=>setSources(Array.from(e.target.files||[]))}/></label><label className="field"><span>本集素材 / 资产（可多选、稍后补充）</span><input type="file" accept="image/*,video/*,audio/*,.pdf,.txt,.md,.docx" multiple disabled={busy} onChange={e=>setRefs(Array.from(e.target.files||[]))}/></label>{error&&<p role="alert" className="error-text">{error}</p>}<button className="primary full large" disabled={busy||!name.trim()||(!created&&!sources.length)}>{busy?'正在保存本集素材…':'添加集并上传素材 →'}</button></form></Modal>;
}
