import { useEffect, useRef, useState } from 'react';
import type { Clip, Episode, Segment } from '../shared/types';
import type { Upload } from './App';
import { downloadText, Empty, Field, inverseMappedTime, mappedTime, media, safeAction, thumbnail, type Command, type State } from './common';
import { ShotRequirements } from './VisualRequirements';
import { Studio, Timeline } from './Studio';
import { AlignmentEditor, ReviewPanel, TakeFeedback } from './Panels';

function GenerationControls({ segment, patch }: { segment: Segment; patch: (patch: Partial<Segment>) => Promise<unknown> }) {
  const followsSource = segment.mode === 'edit';
  return <div className="output-generation-controls" aria-label="视频生成参数">
    <label><span>模式</span><select aria-label="生成方式" value={segment.mode} onChange={e => safeAction(() => patch({ mode: e.target.value as Segment['mode'] }))}><option value="edit">视频编辑</option><option value="reference">全能参考</option></select></label>
    <label><span>时长</span>{followsSource
      ? <output>{segment.duration.toFixed(2)} 秒</output>
      : <select aria-label="输出时长" value={segment.outputDuration ?? Math.min(30, Math.max(4, Math.round(segment.duration)))} onChange={e => safeAction(() => patch({ outputDuration: Number(e.target.value) }))}>{Array.from({ length: 27 }, (_, i) => i + 4).map(seconds => <option value={seconds} key={seconds}>{seconds} 秒</option>)}</select>}</label>
    <label><span>画面比例</span><select aria-label="输出画面比例" value={segment.outputRatio || 'source'} disabled={followsSource} onChange={e => safeAction(() => patch({ outputRatio: e.target.value as Segment['outputRatio'] }))}>
      <option value="source">跟随原片</option><option value="adaptive">自适应</option><option value="16:9">16:9</option><option value="9:16">9:16</option><option value="1:1">1:1</option><option value="4:3">4:3</option><option value="3:4">3:4</option><option value="21:9">21:9</option>
    </select></label>
    <label><span>分辨率</span><select aria-label="输出分辨率" value={segment.outputResolution || 'source'} onChange={e => safeAction(() => patch({ outputResolution: e.target.value as Segment['outputResolution'] }))}>
      <option value="source">跟随原片</option><option value="480p">480p</option><option value="720p">720p</option><option value="1080p">1080p</option>
    </select></label>
  </div>;
}

export function VideoWorkspace({ state, episode, command, upload, importing }: { state: State; episode: Episode; command: Command; upload: Upload; importing: boolean }) {
  const shots = state.shots.filter(s => s.episodeId === episode.id), assets = state.assets.filter(a => a.episodeId === episode.id), segments = state.segments.filter(s => s.episodeId === episode.id);
  const [segmentId, setSegmentId] = useState(''), [takeId, setTakeId] = useState(''), [time, setTime] = useState(0), [mapped, setMapped] = useState(false), [selectedClipId, setSelectedClipId] = useState(''), [panel, setPanel] = useState('generate'), [checkedShots, setCheckedShots] = useState<string[]>([]), [grouping, setGrouping] = useState(false), input = useRef<HTMLInputElement>(null);
  const segment = segments.find(s => s.id === segmentId) || segments[0], takes = state.takes.filter(t => t.kind === 'video' && t.segmentId === segment?.id).sort((a,b) => b.version - a.version), take = takes.find(t => t.id === takeId) || takes.find(t => t.id === segment?.selectedTakeId) || takes[0], clips: Clip[] = segment?.clips || [];
  useEffect(() => { setTime(0); setTakeId(''); setSelectedClipId(segment?.clips[0]?.id || ''); }, [segment?.id]);
  const patch = (patch: Partial<Segment>) => segment ? command('segment.update', { id: segment.id, patch }) : Promise.resolve();
  const busy = (type: string) => state.jobs.some(j => j.type === type && j.targetId === segment?.id && ['queued', 'running', 'waiting', 'uncertain'].includes(j.status));
  const totalChecked = shots.filter(s => checkedShots.includes(s.id)).reduce((sum,s) => sum + s.out - s.in, 0);
  const reviewTime = mapped && take ? mappedTime(take.alignments, time, time) : time;
  return <main className="video-workspace"><aside className="video-segments"><div className="video-sidebar-title"><span className="eyebrow">视频工作台</span><h2>剪辑段</h2><p>每段不超过 30 秒</p></div><div className="segment-list">{segments.map((s,i) => <button key={s.id} className={`segment-item ${s.id === segment?.id ? 'active' : ''}`} onClick={() => setSegmentId(s.id)}><span className="segment-icon">{String(i+1).padStart(2,'0')}</span><span><strong>{s.name}</strong><small>{s.clips.length} 镜 · {s.duration.toFixed(1)} 秒{s.selectedTakeId ? ' · 已选定' : ''}</small></span></button>)}</div><details className="segment-advanced"><summary>添加与管理剪辑段</summary><button className="full" disabled={grouping || !shots.length} onClick={() => { setGrouping(true); safeAction(async () => { try { await command('episode.group', { episodeId: episode.id }); } finally { setGrouping(false); } }); }}>按镜头自动组段</button><p className="hint">也可选择镜头创建一个剪辑段。</p>{shots.map(s => <label className="check" key={s.id}><input type="checkbox" checked={checkedShots.includes(s.id)} onChange={e => setCheckedShots(ids => e.target.checked ? [...ids, s.id] : ids.filter(id => id !== s.id))} />{s.name}</label>)}<button className="full" disabled={!checkedShots.length || totalChecked > 30} onClick={() => safeAction(async () => { const result = await command('segment.create', { episodeId: episode.id, shotIds: checkedShots }) as Segment; setSegmentId(result.id); setCheckedShots([]); })}>新建所选镜头剪辑段 · {totalChecked.toFixed(1)}s</button>{segment && <button className="text-button danger-text" onClick={() => { if (window.confirm(`删除剪辑段「${segment.name}」？素材和历史版本会保留。`)) safeAction(() => command('segment.delete', { id: segment.id })); }}>删除当前剪辑段</button>}</details></aside>
  <div className="video-main">{segment ? <><div className="video-edit-top"><div className="video-center"><Studio clips={take?.sourceClips?.length ? take.sourceClips : clips} shots={shots} assets={assets} take={take} time={time} setTime={setTime} tab="video" mapped={mapped} setMapped={setMapped} outputControls={<GenerationControls segment={segment} patch={patch} />} /><section className="takes-shelf"><header className="row spread"><div><h3>生成版本</h3><p className="muted">{takes.length ? `${takes.length} 个版本 · 点击比较` : '生成后在这里比较与选择'}</p></div><button disabled={importing} onClick={() => input.current?.click()}>导入视频版本</button><input ref={input} type="file" aria-label="导入视频版本" accept="video/*" multiple hidden onChange={e => { const files = Array.from(e.target.files || []); if (files.length) safeAction(() => upload(files, 'video-take', { segmentId: segment.id })); e.target.value = ''; }} /></header><div className="take-strip">{takes.map(t => <button key={t.id} className={`take-tile ${take?.id === t.id ? 'selected' : ''}`} onClick={() => { setTakeId(t.id); setTime(0); }}><div><img src={thumbnail(t.assetId)} alt={`视频版本 ${t.version}`} /><span>V{t.version}</span></div><footer><span>{segment.selectedTakeId === t.id ? '成片已选定' : t.status === 'approved' ? '已批准' : t.status === 'rejected' ? '已退回' : '待审片'}</span></footer>{t.sourceRevision !== segment.revision && <small className="stale-note">剪辑已修改，请复核</small>}</button>)}</div></section></div>
  <aside className="video-properties"><div className="segmented"><button className={panel === 'generate' ? 'active' : ''} onClick={() => setPanel('generate')}>生成与版本</button><button className={panel === 'review' ? 'active' : ''} onClick={() => setPanel('review')}>审片与批注</button></div><div className="video-properties-scroll">{panel === 'generate' ? <><section className="property-section"><h2>{segment.name}</h2><p className="hint">{segment.duration.toFixed(2)} 秒 · {segment.clips.length} 个片段。提示词已自动整理。</p><button className="primary large full" disabled={!segment.prompt.trim() || segment.duration < 4 || segment.duration > 30 || busy('segment.generate')} onClick={() => safeAction(() => command('segment.generate', { id: segment.id }))}>{busy('segment.generate') ? '视频生成中…' : '✧ 生成新视频版本'}</button><p className="hint">实拍片段会自动准备。生成结果保留为新版本。</p>{segment.duration < 4 && <p className="error-text">这一段不足 4 秒，请在时间轴延长或加入其他镜头。</p>}{segment.duration > 30 && <p className="error-text">这一段超过 30 秒，请裁剪或拆成多段。</p>}</section>{take && <section className="property-section"><h3>当前版本 · V{take.version}</h3><button className={`full ${segment.selectedTakeId === take.id ? 'secondary' : 'primary'}`} onClick={() => safeAction(async () => { await command('take.approve', { id: take.id, scope: 'shot' }); })}>{segment.selectedTakeId === take.id ? '✓ 已选为成片' : '选择此版本用于成片'}</button><div className="row"><button onClick={() => setPanel('review')}>审片与批注</button><button className="text-button danger-text" onClick={() => safeAction(() => command('take.reject', { id: take.id }))}>退回</button></div><a className="text-button" href={media(take.assetId)} download>下载当前版本 ↗</a></section>}
  <details className="property-section"><summary>本段逐镜画面要求</summary>{[...new Set(clips.map(c=>c.shotId))].map(id=>{const shot=shots.find(s=>s.id===id);return shot?<ShotRequirements key={id} state={state} shot={shot} command={command} sceneControls/>:null;})}</details><details className="property-section"><summary>提示词与生成选项</summary><Field label="分段提示词" value={segment.prompt} onSave={prompt => patch({ prompt })} multiline rows={10} /><button disabled={busy('ai.segmentPrompt')} onClick={() => safeAction(() => command('ai.segmentPrompt', { segmentId: segment.id }))}>Codex 重新编写</button><button onClick={() => downloadText(`${segment.name}-视频提示词.txt`, segment.prompt)}>下载提示词</button><Field label="剪辑段名称" value={segment.name} onSave={name => patch({ name })} /><button disabled={busy('segment.prepare')} onClick={() => safeAction(() => command('segment.prepare', { id: segment.id }))}>单独导出实拍剪辑段</button>{segment.sourceAssetId && <a className="text-button" href={media(segment.sourceAssetId)} download>下载实拍剪辑段 ↗</a>}</details>{take && <><details className="property-section"><summary>反馈与提示词返修</summary><TakeFeedback key={take.id} take={take} command={command} /></details><details className="property-section"><summary>逐镜对齐与映射</summary><AlignmentEditor take={take} command={command} sourceClips={clips} generatedDuration={assets.find(a => a.id === take.assetId)?.duration} /></details></>}</> : <ReviewPanel state={state} take={take} time={reviewTime} setTime={t => setTime(mapped && take ? inverseMappedTime(take.alignments, t) : t)} command={command} />}</div></aside></div><Timeline segment={segment} clips={clips} shots={shots} assets={assets} time={time} setTime={setTime} command={command} selectedClipId={selectedClipId} setSelectedClipId={setSelectedClipId} /></> : <div className="gallery-empty"><Empty title="准备剪辑段">按镜头顺序自动组段后，就可以开始制作视频。</Empty><button className="primary large" disabled={grouping} onClick={() => { setGrouping(true); safeAction(async () => { try { await command('episode.group', { episodeId: episode.id }); } finally { setGrouping(false); } }); }}>{grouping ? '正在整理…' : '自动组段并准备提示词'}</button></div>}</div></main>;
}
